In [2]:
import pandas as pd
import numpy as np
import scipy.stats

In [3]:
data = pd.read_csv('gene_high_throughput_sequencing.csv')

In [4]:
data.head()

Patient_id Diagnosis  LOC643837  LOC100130417     SAMD11  \
0  STT5425_Breast_001_normal    normal   1.257614      2.408148  13.368622   
1  STT5427_Breast_023_normal    normal   4.567931     16.602734  42.477752   
2  STT5430_Breast_002_normal    normal   2.077597      3.978294  12.863214   
3  STT5439_Breast_003_normal    normal   2.066576      8.520713  14.466035   
4  STT5441_Breast_004_normal    normal   2.613616      3.434965  12.682222   

       NOC2L     KLHL17    PLEKHN1   C1orf170       HES4    ...         CLIC2  \
0   9.494779  20.880435  12.722017   9.494779  54.349694    ...      4.761250   
1  25.562376  23.221137  11.622386  14.330573  72.445474    ...      6.871902   
2  13.728915  14.543176  14.141907   6.232790  57.011005    ...      7.096343   
3   7.823932   8.520713   2.066576  10.870009  53.292034    ...      5.200770   
4  10.543189  26.688686  12.484822   1.364917  67.140393    ...     11.227770   

     RPS4Y1       ZFY      PRKY     USP9Y     DDX3Y       CD24  CYorf15B  \
0  1.257614  1.257614  1.257614  1.257614  1.257614  23.268694  1.257614   
1  1.815112  1.815112  1.815112  1.815112  1.815112  10.427023  1.815112   
2  2.077597  2.077597  2.077597  2.077597  2.077597  22.344226  2.077597   
3  2.066576  2.066576  2.066576  2.066576  2.066576  49.295538  2.066576   
4  1.364917  1.364917  1.364917  1.364917  1.364917  23.627911  1.364917   

      KDM5D    EIF1AY  
0  1.257614  1.257614  
1  1.815112  1.815112  
2  2.077597  2.077597  
3  2.066576  2.066576  
4  1.364917  1.364917  

[5 rows x 15750 columns]

In [5]:
del data['Patient_id']

In [6]:
pd.unique(data['Diagnosis'])

array(['normal', 'early neoplasia', 'cancer'], dtype=object)

In [7]:
data_normal = pd.DataFrame(columns = data.columns)
data_early_neoplasia = pd.DataFrame(columns = data.columns)
data_cancer = pd.DataFrame(columns = data.columns)

In [8]:
for i in range(72):
    if data['Diagnosis'][i] == 'normal':
        data_normal = data_normal.append(data.loc[i])
    if data['Diagnosis'][i] == 'early neoplasia':
        data_early_neoplasia = data_early_neoplasia.append(data.loc[i])
    if data['Diagnosis'][i] == 'cancer':
        data_cancer = data_cancer.append(data.loc[i])

In [9]:
del data_normal['Diagnosis']
del data_early_neoplasia['Diagnosis']
del data_cancer['Diagnosis']

In [30]:
p_values_1 = scipy.stats.ttest_ind(data_normal, data_early_neoplasia, equal_var=False)[1]

In [31]:
p_values_2 = scipy.stats.ttest_ind(data_early_neoplasia, data_cancer, equal_var=False)[1]

In [32]:
len(p_values_1)==len(p_values_2)

True

In [33]:
counter_1 = 0
counter_2 = 0
for i in range(len(p_values_1)):
    if p_values_1[i] < 0.05:
        counter_1 += 1
    if p_values_2[i] < 0.05:
        counter_2 += 1   

In [34]:
print 'Question 1: first =', counter_1,'second =', counter_2

Question 1: first = 1575 second = 3490


In [35]:
file = open('Answer_1_1.txt','w') 
file.write(str(counter_1)) 
file.close()
file = open('Answer_1_2.txt','w') 
file.write(str(counter_2)) 
file.close()

In [59]:
import statsmodels.stats.multitest as smm

In [100]:
smm_3 = smm.multipletests(p_values_1, alpha = 0.025, method = 'holm')

In [101]:
smm_3

(array([False, False, False, ..., False, False, False]),
 array([1.        , 0.50017368, 1.        , ..., 1.        , 1.        ,
        1.        ]),
 1.6076827300537389e-06,
 1.58750317500635e-06)

In [108]:
smm_4 = smm.multipletests(abs(p_values_2), alpha = 0.025, method = 'holm')

In [109]:
smm_4

(array([False, False, False, ..., False, False, False]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 1.6076827300537389e-06,
 1.58750317500635e-06)

In [110]:
len(smm_3[1])==len(smm_4[1])

True

In [130]:
counter_3 = 0
counter_4 = 0
for i in range(len(smm_1[1])):
    if smm_3[1][i] < 0.025:
        counter_3 += 1
    if abs(smm_4[1][i]) < 0.025:
        counter_4 += 1  
#counter_4 = 77

In [131]:
print 'Question 2: first =', counter_3,'second =', counter_4

Question 2: first = 2 second = 79


In [75]:
file = open('Answer_2_1.txt','w') 
file.write(str(counter_3)) 
file.close()
file = open('Answer_2_2.txt','w') 
file.write(str(counter_4)) 
file.close()

In [89]:
smm_5 = smm.multipletests(p_values_1, alpha = 0.025, method = 'fdr_bh')
smm_6 = smm.multipletests(p_values_2, alpha = 0.025, method = 'fdr_bh')

In [90]:
len(smm_5[1])==len(smm_6[1])

True

In [126]:
counter_5 = 0
counter_6 = 0
for i in range(len(smm_3[1])):
    if smm_5[1][i] < 0.025:
        counter_5 += 1
    if smm_6[1][i] < 0.025:
        counter_6 += 1

In [127]:
print 'Question 3: first =', counter_5,'second =', counter_6

Question 3: first = 4 second = 832


In [95]:
file = open('Answer_3_1.txt','w') 
file.write(str(counter_5)) 
file.close()
file = open('Answer_3_2.txt','w') 
file.write(str(counter_6)) 
file.close()

In [125]:
for i in range(len(p_values_2)):
    if p_values_2[i]>0.9999:
        print p_values_2[i]

0.9999821281566382
0.9999042881650277
